# 1. Preload the wallpaper into memory (required)
preload = /home/seth/Pictures/Wallpapers/nixos-journey.png

# 2. Set the wallpaper for your monitor
# The first argument is the monitor name. empty means "all monitors"
wallpaper = ,/home/seth/Pictures/Wallpapers/nixos-journey.png

# Optional: Disable the "splash" text at the bottom
splash = false
